name: Deploy Terraform and Docker

on:
  push:
    branches:
      - main2

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: "sa-east-1"
  TF_VAR_aws_region: "sa-east-1"

jobs:
  terraform:
    name: Provision Infrastructure with Terraform
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configurar o AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      # 4. Inicializar Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: infra

#      # 5. Importar Recursos Existentes
#      - name: Import Existing Resources
#        shell: bash
#        working-directory: infra
#        run: |
#          terraform state list aws_vpc.my_vpc || terraform import aws_vpc.my_vpc vpc-025c03cbc0a07b1e1
#          terraform state list aws_subnet.my_subnets[0] || terraform import aws_subnet.my_subnets[0] subnet-0f7f24c019c63fab3
#          terraform state list aws_subnet.my_subnets[1] || terraform import aws_subnet.my_subnets[1] subnet-09d75a9c2188e33a2
#          terraform state list aws_security_group.my_sg || terraform import aws_security_group.my_sg sg-03f55974474dffa57
#          terraform state list aws_ecs_cluster.my_cluster || terraform import aws_ecs_cluster.my_cluster my-ecs-cluster
#          terraform state list aws_ecr_repository.my_api || terraform import aws_ecr_repository.my_api my-api-repository
#          terraform state list aws_iam_role.ecs_task_execution_role || terraform import aws_iam_role.ecs_task_execution_role ecsTaskExecutionRole
#

      # 5. Planejar Infraestrutura
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infra

      # 6. Aplicar Infraestrutura
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: infra

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: terraform # Garante que o Terraform finalize antes do Docker

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: List Files
        run: ls -R

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-api-repository:latest -f api-test/Dockerfile api-test/

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-api-repository:latest