name: Deploy Terraform and Docker

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provision Infrastructure with Terraform
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configurar o AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      # 4. Inicializar Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: infra

      # 5. Importar Recursos Existentes
      - name: Import Existing Resources
        run: |
          if ! terraform import aws_vpc.my_vpc <vpc-id>; then echo "VPC already imported"; fi
          if ! terraform import aws_subnet.my_subnets[0] <subnet-id-1>; then echo "Subnet 1 already imported"; fi
          if ! terraform import aws_subnet.my_subnets[1] <subnet-id-2>; then echo "Subnet 2 already imported"; fi
          if ! terraform import aws_security_group.my_sg <security-group-id>; then echo "Security Group already imported"; fi
          if ! terraform import aws_ecs_cluster.my_cluster my-ecs-cluster; then echo "ECS Cluster already imported"; fi
          if ! terraform import aws_ecr_repository.my_api my-api-repository; then echo "ECR Repository already imported"; fi

      # 6. Planejar Infraestrutura
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infra

      # 7. Aplicar Infraestrutura
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: infra

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: terraform # Garante que o Terraform finalize antes do Docker

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: List Files
        run: ls -R

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-api-repository:latest -f api-test/Dockerfile api-test/

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-api-repository:latest